#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  title: demo-verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # convert your UI to the dark side
  # darkMode: true
  # logo: http://somedomain/somelogo.png
  # favicon: http://somedomain/favicon.ico | /path/favicon.ico

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   设置默认语言为中文，默认值为en-US
  i18n:
    web: zh-CN


auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # 设置为-1.即禁止注册
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs: { type: stdout, format: pretty, level: http }

# 使用jwt身份验证
security:
  legacy: false
  api:
    jwt:
      sign:
        expiresIn: 30d
        notBefore: 0
  web:
    sign:
      expiresIn: 7d
      notBefore: 0


#experiments:
#  # support for npm token command
#  token: false
#  # disable writing body size to logs, read more on ticket 1912
#  bytesin_off: false
#  # enable tarball URL redirect for hosting tarball with a different server, the tarball_url_redirect can be a template string
#  tarball_url_redirect: 'https://mycdn.com/verdaccio/${packageName}/${filename}'
#  # the tarball_url_redirect can be a function, takes packageName and filename and returns the url, when working with a js configuration file
#  tarball_url_redirect(packageName, filename) {
#    const signedUrl = // generate a signed url
#    return signedUrl;
#  }

# This affect the web and api (not developed yet)
#i18n:
#web: en-US


# 单个通知
# notify:
#   method: POST
#   headers: [{'Content-Type': 'application/json;charset=utf-8'}]
#   endpoint: https://oapi.dingtalk.com/robot/send?access_token=你的token码
#   content: '{"msgtype": "markdown","at": { "isAtAll": true },"markdown":{"title":"FBI WARNING!您有新的包裹,请注意查收!","text": "![](https://图片链接)\n\n#### 包名: {{ name }} -> ([更多信息](http://npm.h3yun.net:4873/-/web/detail/{{name}}))\n {{#if  description}} > {{ description }}{{/if}}  \n\n{{#if dist-tags.latest }}稳定版(latest):**{{ name }}@{{ dist-tags.latest }}**{{/if}} \n\n{{#if dist-tags.dev }}开发版(dev):**{{ name }}@{{ dist-tags.dev }}**{{/if}} \n\n{{#if dist-tags.alpha }}alpha版本:**{{ name }}@{{ dist-tags.alpha }}**{{/if}} \n\n{{#if dist-tags.alpha }}next版本:**{{ name }}@{{ dist-tags.next }}**{{/if}}\n\n发布人:**{{ publisher.name }}**  \n\n 欢迎各位大佬使用,有问题请及时反馈,谢谢! \n\n  "} }'

  # content: '{"color":"green","message":"New package published: * {{ name }}*","notify":true,"message_format":"text"}'

# 多个通知
notify:
  'example-dingtalk-chat':
    method: POST
    headers: [{'Content-Type': 'application/json'}]
    endpoint: https://oapi.dingtalk.com/robot/send?access_token=你的token码
    content: '{"msgtype": "markdown","at": { "isAtAll": true },"markdown":{"title":"FBI WARNING!您有新的包裹,请注意查收!","text": "![](https://imgconvert.csdnimg.cn/aHR0cHM6Ly9wMy1qdWVqaW4uYnl0ZWltZy5jb20vdG9zLWNuLWktazN1MWZicGZjcC9kOWVmOTQ0NTUwMGM0NDY4YTc4ZTg2NTIwNDRlMWMxNH50cGx2LWszdTFmYnBmY3Atem9vbS0xLmltYWdl?x-oss-process=image/format,png)\n\n#### 包名: {{ name }} -> ([更多信息](http://npm.h3yun.net:4873/-/web/detail/{{name}}))\n {{#if  description}} > {{ description }}{{/if}}  \n\n{{#if dist-tags.latest }}稳定版(latest):**{{ name }}@{{ dist-tags.latest }}**{{/if}} \n\n{{#if dist-tags.dev }}开发版(dev):**{{ name }}@{{ dist-tags.dev }}**{{/if}} \n\n{{#if dist-tags.alpha }}alpha版本:**{{ name }}@{{ dist-tags.alpha }}**{{/if}} \n\n{{#if dist-tags.alpha }}next版本:**{{ name }}@{{ dist-tags.next }}**{{/if}}\n\n发布人:**{{ publisher.name }}**  \n\n 欢迎各位大佬使用,有问题请及时反馈,谢谢! \n\n  "} }'


# 模板
# iterate all versions
# {{ name }}{{#each versions}} v{{version}}{{/each}}

# publisher and `dist-tag` package published
# {{ publisher.name }} has published {{ publishedPackage }}


# 监听地址
listen: 0.0.0.0:4873